<a href="https://colab.research.google.com/github/kavyajeetbora/player_scout_2019/blob/master/data/Similar_players.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0. Import

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Loading the data

In [0]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Data Science/Personal Projects/FIFA datset/FullData.csv')
df.head()

                Name Nationality  ... GK_Handling  GK_Reflexes
0  Cristiano Ronaldo    Portugal  ...          11           11
1       Lionel Messi   Argentina  ...          11            8
2             Neymar      Brazil  ...           9           11
3        Luis Suárez     Uruguay  ...          25           37
4       Manuel Neuer     Germany  ...          90           89

[5 rows x 53 columns]

In [0]:
basic_info = df[['Name', 'Nationality', 'National_Kit', 'Club',
       'Rating', 'Height', 'Weight', 'Preffered_Foot', 'Birth_Date', 'Age',
       'Preffered_Position']]
basic_info.head()

                Name Nationality  ...  Age Preffered_Position
0  Cristiano Ronaldo    Portugal  ...   32              LW/ST
1       Lionel Messi   Argentina  ...   29                 RW
2             Neymar      Brazil  ...   25                 LW
3        Luis Suárez     Uruguay  ...   30                 ST
4       Manuel Neuer     Germany  ...   31                 GK

[5 rows x 11 columns]

In [0]:
basic_info.dtypes

Name                   object
Nationality            object
National_Kit          float64
Club                   object
Rating                  int64
Height                 object
Weight                 object
Preffered_Foot         object
Birth_Date             object
Age                     int64
Preffered_Position     object
dtype: object

In [0]:
basic_info1 = basic_info.copy()
basic_info1['Rating'] = basic_info1['Rating'].apply(lambda x: str(x))

basic_info2 = basic_info1.copy()
basic_info2['Age'] = basic_info2['Age'].apply(lambda x: str(x))
basic_info2.dtypes

Name                   object
Nationality            object
National_Kit          float64
Club                   object
Rating                 object
Height                 object
Weight                 object
Preffered_Foot         object
Birth_Date             object
Age                    object
Preffered_Position     object
dtype: object

In [0]:
basic_info_dict = {}
for i in basic_info.index:
    basic_info_dict[i] = basic_info2.iloc[i,:].values.tolist()

In [0]:
df.shape

(17588, 53)

In [0]:
df.dtypes

Name                   object
Nationality            object
National_Position      object
National_Kit          float64
Club                   object
Club_Position          object
Club_Kit              float64
Club_Joining           object
Contract_Expiry       float64
Rating                  int64
Height                 object
Weight                 object
Preffered_Foot         object
Birth_Date             object
Age                     int64
Preffered_Position     object
Work_Rate              object
Weak_foot               int64
Skill_Moves             int64
Ball_Control            int64
Dribbling               int64
Marking                 int64
Sliding_Tackle          int64
Standing_Tackle         int64
Aggression              int64
Reactions               int64
Attacking_Position      int64
Interceptions           int64
Vision                  int64
Composure               int64
Crossing                int64
Short_Pass              int64
Long_Pass               int64
Acceleration            int64
Speed                   int64
Stamina                 int64
Strength                int64
Balance                 int64
Agility                 int64
Jumping                 int64
Heading                 int64
Shot_Power              int64
Finishing               int64
Long_Shots              int64
Curve                   int64
Freekick_Accuracy       int64
Penalties               int64
Volleys                 int64
GK_Positioning          int64
GK_Diving               int64
GK_Kicking              int64
GK_Handling             int64
GK_Reflexes             int64
dtype: object

## 2. Feature Selection for similarity

For finding out the cosine similarities we will consider/not consider the following features - 

- overall rating, preferred_foot, age and preferred position, weak_foot, work_rate, and all the other features 
- One caveat: check whether the model is able to capture similarities between GKs
- Most of the columns are to be considered for the model, hence we will drop the columns that arent required.
- Since we our aim is to find players similar to their playing style, we drop off columns that are irrelevant like contract, country etc

In [0]:
df.columns

Index(['Name', 'Nationality', 'National_Position', 'National_Kit', 'Club',
       'Club_Position', 'Club_Kit', 'Club_Joining', 'Contract_Expiry',
       'Rating', 'Height', 'Weight', 'Preffered_Foot', 'Birth_Date', 'Age',
       'Preffered_Position', 'Work_Rate', 'Weak_foot', 'Skill_Moves',
       'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle',
       'Standing_Tackle', 'Aggression', 'Reactions', 'Attacking_Position',
       'Interceptions', 'Vision', 'Composure', 'Crossing', 'Short_Pass',
       'Long_Pass', 'Acceleration', 'Speed', 'Stamina', 'Strength', 'Balance',
       'Agility', 'Jumping', 'Heading', 'Shot_Power', 'Finishing',
       'Long_Shots', 'Curve', 'Freekick_Accuracy', 'Penalties', 'Volleys',
       'GK_Positioning', 'GK_Diving', 'GK_Kicking', 'GK_Handling',
       'GK_Reflexes'],
      dtype='object')

In [0]:
df2 = df.copy()
df2 = df.drop(columns=['Nationality', 'National_Position', 'National_Kit', 'Club','Club_Position', 'Club_Kit', 'Club_Joining', 'Contract_Expiry', 'Birth_Date'])
df2.head()

                Name  Rating  Height  ... GK_Kicking GK_Handling  GK_Reflexes
0  Cristiano Ronaldo      94  185 cm  ...         15          11           11
1       Lionel Messi      93  170 cm  ...         15          11            8
2             Neymar      92  174 cm  ...         15           9           11
3        Luis Suárez      92  182 cm  ...         31          25           37
4       Manuel Neuer      92  193 cm  ...         95          90           89

[5 rows x 44 columns]

## 3. Data Cleaning

- Look for null values and fixing it
- Standardising the columns
- Look for outliers in each numerical columns

### 3.1 Fixing Null Values

In [0]:
df2.isnull().sum()

Name                  0
Rating                0
Height                0
Weight                0
Preffered_Foot        0
Age                   0
Preffered_Position    0
Work_Rate             0
Weak_foot             0
Skill_Moves           0
Ball_Control          0
Dribbling             0
Marking               0
Sliding_Tackle        0
Standing_Tackle       0
Aggression            0
Reactions             0
Attacking_Position    0
Interceptions         0
Vision                0
Composure             0
Crossing              0
Short_Pass            0
Long_Pass             0
Acceleration          0
Speed                 0
Stamina               0
Strength              0
Balance               0
Agility               0
Jumping               0
Heading               0
Shot_Power            0
Finishing             0
Long_Shots            0
Curve                 0
Freekick_Accuracy     0
Penalties             0
Volleys               0
GK_Positioning        0
GK_Diving             0
GK_Kicking            0
GK_Handling           0
GK_Reflexes           0
dtype: int64

The data looks clean as there is no null values

### 3.2 Standardising the columns

- Height and weight needs to be a numerical value, which is stored as string

In [0]:
df3 = df2.copy()
df3['Height'] = df3['Height'].apply(lambda x: int(x.split('cm')[0]))

df4 = df3.copy()
df4['Weight'] = df4['Weight'].apply(lambda x: int(x.split('kg')[0]))

df4[['Height','Weight']].dtypes

Height    int64
Weight    int64
dtype: object

## 4. Data Processing 

- Converting categorial variables into one_hot_encoded form. Columns - 
    - Work_Rate
    - Preferred Position
    - Preferred Foot

In [0]:
len(df4['Preffered_Foot'].unique())

2

there are only 2 values Left and right hence only one column for it whether the player is right footed or not

In [0]:
df5 = df4.copy()
df5['right_foot'] = df5['Preffered_Foot'].apply(lambda x: 1 if (x=='Right') else 0)
df5.head()

                Name  Rating  Height  ...  GK_Handling GK_Reflexes  right_foot
0  Cristiano Ronaldo      94     185  ...           11          11           1
1       Lionel Messi      93     170  ...           11           8           0
2             Neymar      92     174  ...            9          11           1
3        Luis Suárez      92     182  ...           25          37           1
4       Manuel Neuer      92     193  ...           90          89           1

[5 rows x 45 columns]

In [0]:
print(len(df5['Preffered_Position'].unique()))
positions = df5['Preffered_Position'].unique()
positions

292

array(['LW/ST', 'RW', 'LW', 'ST', 'GK', 'CB', 'LW/LM', 'CM/CDM', 'CAM/LW',
       'CM/CAM', 'ST/LW', 'CAM/RM/LM', 'LM/CAM', 'ST/RM', 'RB/CM', 'CM',
       'CAM/RM', 'CAM/LM', 'RM/RW', 'ST/CAM', 'LB/CM', 'RM/CAM',
       'CF/CAM/ST', 'CDM/CM', 'CM/CDM/LM', 'LB', 'LW/CAM', 'RW/CAM',
       'LM/LW', 'CAM/CDM', 'CAM/CM', 'CB/CDM', 'RB', 'CM/RM', 'LB/LM',
       'LM', 'CB/RB', 'CAM', 'CM/LW', 'CDM', 'RM', 'CB/LB', 'LM/RM',
       'ST/RW', 'CM/RW', 'RW/LW', 'CM/LM', 'CF/ST', 'ST/LM', 'RB/CB',
       'LM/CM/CAM', 'CAM/CF', 'CAM/ST', 'LW/CAM/LM', 'RB/RM', 'RM/LM',
       'CAM/LM/LW', 'LM/ST', 'RW/RM', 'CAM/ST/CF', 'CDM/CB', 'LB/CB',
       'RB/RWB', 'RW/ST', 'LW/CF', 'CDM/RM', 'RM/ST', 'LB/CDM', 'LM/RW',
       'RM/LW', 'RW/CM/LW', 'RB/RW', 'LB/RB', 'LB/LWB', 'CAM/RW', 'LW/RW',
       'CM/RB/CDM', 'CDM/RB', 'CM/CAM/LM', 'CF/RM', 'RB/LB', 'CF/CAM',
       'LM/CM', 'CF/LW', 'RM/CAM/ST', 'ST/RM/RW', 'CAM/CM/LM',
       'RB/RW/RWB', 'RM/RB', 'CM/CB', 'CAM/LM/CM', 'LWB/LB', 'CM/RB/RM',
       'LM/RB', 'ST/CF', 'LW/CAM/CF', 'CM/CF', 'CAM/LM/CDM', 'LM/LW/LB',
       'LW/CM', 'CDM/CAM', 'RWB/LM', 'CM/CAM/RM', 'CM/CDM/CAM', 'RM/RWB',
       'CAM/ST/CM', 'RWB/RB', 'LM/CDM', 'RB/CDM', 'CDM/CM/RB',
       'CDM/CB/RB', 'CF/LM', 'RW/LW/RM', 'LM/LB', 'RM/CF', 'CM/RM/CDM',
       'LM/LWB', 'RM/CM', 'LM/RM/RW', 'CAM/CM/CDM', 'RM/CF/LW',
       'CAM/LM/RM', 'CM/CF/RW', 'LB/CAM', 'RW/LW/CF', 'RM/LM/CAM',
       'LW/RM', 'RM/CM/CAM', 'LB/LW', 'CDM/CM/CAM', 'RW/RB', 'RM/CDM/LM',
       'CF/CAM/RM', 'RWB/RM', 'CB/RB/CM', 'LB/LM/LW', 'CDM/LB', 'CF/RW',
       'CAM/RB', 'RB/RW/LW', 'LM/RM/CF', 'RW/CM', 'CB/CM', 'RW/LM',
       'ST/LM/RB', 'CM/RB', 'LM/RM/CM', 'LB/CDM/CM', 'CB/LB/CDM',
       'CAM/RW/LW', 'CM/RM/LM', 'CAM/CF/CDM', 'LW/LM/RM', 'RB/CB/RWB',
       'CM/LB', 'CB/LM', 'RW/LM/LW', 'LB/RM', 'LM/CF', 'RM/LB', 'CB/RWB',
       'ST/LW/RW', 'LWB/CDM', 'CM/LM/CB', 'CM/LM/RM', 'RM/CAM/LM',
       'CM/RM/CAM', 'ST/LM/CF', 'RB/LM', 'CF/RM/LM', 'ST/RW/LW', 'CAM/LB',
       'RM/RW/RWB', 'CAM/RM/CM', 'LM/RM/ST', 'ST/CM', 'LWB/CB', 'ST/RWB',
       'CDM/LM', 'ST/RM/CAM', 'CAM/CM/RM', 'CM/LM/CDM', 'CF/CM',
       'CAM/CDM/LM', 'LB/LWB/CM', 'RM/CM/CDM', 'RM/CDM', 'RM/LW/LM',
       'CM/ST', 'CAM/RM/LW', 'CAM/CM/CF', 'LW/LB', 'LWB/CM/RWB',
       'RW/CF/RM', 'RW/CF', 'RB/RM/LM', 'LB/RW', 'LWB/LW', 'CAM/RWB',
       'RM/RW/LW', 'CM/RM/LB', 'LW/RW/CAM', 'RM/LM/RB', 'LM/CAM/ST',
       'RM/CM/LWB', 'CB/LM/LWB', 'LM/ST/CB', 'LWB/RWB', 'CB/LWB',
       'RB/RM/CDM', 'CF', 'RW/CAM/ST', 'LWB/RM', 'CDM/RM/RB', 'RM/CAM/CM',
       'ST/RW/RM', 'CAM/RM/ST', 'CAM/CM/ST', 'LM/CM/RM', 'RM/CAM/CDM',
       'RWB/LB', 'ST/RW/LM', 'RB/CAM', 'ST/CAM/LM', 'CDM/RB/RM', 'CM/LWB',
       'ST/CF/CAM', 'CB/ST', 'ST/LM/CAM', 'RB/CAM/CM', 'RW/RM/LW',
       'CM/RW/LW', 'LM/CAM/RB', 'ST/RM/LW', 'RM/LW/RW', 'CDM/CAM/RM',
       'LM/ST/CAM', 'RWB', 'CDM/RM/CAM', 'RWB/LWB', 'LM/RM/LB', 'CM/RWB',
       'RB/LM/CAM', 'RB/CDM/CB', 'LWB/LM', 'LM/CAM/CM', 'CAM/RW/ST',
       'LW/ST/CF', 'CDM/LM/CAM', 'CAM/CF/ST', 'RW/LW/CM', 'RB/RM/LB',
       'RM/LM/CDM', 'ST/LW/LM', 'RWB/CM', 'CM/LM/CAM', 'LB/LWB/RWB',
       'RB/RM/CAM', 'LB/LM/RM', 'CDM/RB/CB', 'LW/CAM/ST', 'LWB',
       'CDM/RWB', 'LM/CM/CB', 'CB/CDM/CM', 'RB/ST', 'RW/ST/CM',
       'RW/LW/ST', 'CM/ST/CDM', 'ST/CB', 'LW/LM/LB', 'RW/LB', 'CM/CDM/RM',
       'ST/CF/RM', 'CAM/LM/ST', 'RM/LM/CM', 'RW/RM/ST', 'CAM/LWB',
       'CDM/LM/RM', 'CM/CDM/RB', 'LW/LWB', 'RM/CB', 'RB/LWB', 'RB/LB/CDM',
       'LB/ST', 'RW/ST/LM', 'ST/LM/RM', 'CB/CM/RM', 'ST/CDM', 'CB/RM',
       'ST/LB', 'RB/LB/CM'], dtype=object)

We can see there are 200 positions but these are combinations, we can separate out each individual positions and create a multi-hot encoded vector since the position variable is nominal categorial variable.

- Extracting the inidividual positions first

In [0]:
all_positions = []
for pos in positions:
    tokens = pos.split('/')
    all_positions.extend(tokens)

unique_positions = list(set(all_positions))
print(len(unique_positions))
unique_positions.remove('GK')
unique_positions = sorted(unique_positions)
print(unique_positions)

15
['CAM', 'CB', 'CDM', 'CF', 'CM', 'LB', 'LM', 'LW', 'LWB', 'RB', 'RM', 'RW', 'RWB', 'ST']

We can see now we have only 15 positions instead of 200+ positions. Based on this we will hot encode the positions for each player based on their preferences.

Also before one hot encoding, to avoid dummy variable trap we will drop the position GK since it is not seen in combination, and also it is true in real, player who plays as a goal keeper, rarely play in other positions.

In [0]:
position_encoding = {}
for index, pref_pos in zip(df5.index,df5['Preffered_Position'].values):
    multi_hot_encoding = [0]*14
    tokens = pref_pos.split('/')
    for i,pos in enumerate(unique_positions):
        if pos in tokens:
            multi_hot_encoding[i] = 1

    position_encoding[index] = multi_hot_encoding

In [0]:
position_encoding[0]

[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]

In [0]:
pos_encodings = pd.DataFrame.from_dict(data=position_encoding,orient='index',columns=unique_positions)
pos_encodings.head()

   CAM  CB  CDM  CF  CM  LB  LM  LW  LWB  RB  RM  RW  RWB  ST
0    0   0    0   0   0   0   0   1    0   0   0   0    0   1
1    0   0    0   0   0   0   0   0    0   0   0   1    0   0
2    0   0    0   0   0   0   0   1    0   0   0   0    0   0
3    0   0    0   0   0   0   0   0    0   0   0   0    0   1
4    0   0    0   0   0   0   0   0    0   0   0   0    0   0

In [0]:
df5.shape

(17588, 45)

In [0]:
df6 = df5.copy()
df6 = pd.concat([df6,pos_encodings], axis='columns')
df6.head()

                Name  Rating  Height  Weight  ... RM  RW RWB ST
0  Cristiano Ronaldo      94     185      80  ...  0   0   0  1
1       Lionel Messi      93     170      72  ...  0   1   0  0
2             Neymar      92     174      68  ...  0   0   0  0
3        Luis Suárez      92     182      85  ...  0   0   0  1
4       Manuel Neuer      92     193      92  ...  0   0   0  0

[5 rows x 59 columns]

In [0]:
print(len(df6['Work_Rate'].unique()))
df6['Work_Rate'].unique()

9

array(['High / Low', 'Medium / Medium', 'High / Medium', 'Medium / Low',
       'High / High', 'Medium / High', 'Low / High', 'Low / Medium',
       'Low / Low'], dtype=object)

In [0]:
work_rate_dummies = pd.get_dummies(df6['Work_Rate'])
work_rate_dummies.head()

   High / High  High / Low  ...  Medium / Low  Medium / Medium
0            0           1  ...             0                0
1            0           0  ...             0                1
2            0           0  ...             0                0
3            0           0  ...             0                0
4            0           0  ...             0                1

[5 rows x 9 columns]

In [0]:
df7 = df6.copy()
df7 = pd.concat([df7,work_rate_dummies.drop('Low / Low', axis='columns')], axis='columns')
df7.head()

                Name  Rating  ...  Medium / Low  Medium / Medium
0  Cristiano Ronaldo      94  ...             0                0
1       Lionel Messi      93  ...             0                1
2             Neymar      92  ...             0                0
3        Luis Suárez      92  ...             0                0
4       Manuel Neuer      92  ...             0                1

[5 rows x 67 columns]

Dropping the columns that are not required - 

One more point, The height and the weight is irrelevant to find similarilities in playing, hence to be removed

In [0]:
df8 = df7.copy()
df8 = df8.drop(['Preffered_Foot','Preffered_Position','Work_Rate','Height', 'Weight'],axis='columns')
df8.head()

                Name  Rating  Age  ...  Medium / High  Medium / Low  Medium / Medium
0  Cristiano Ronaldo      94   32  ...              0             0                0
1       Lionel Messi      93   29  ...              0             0                1
2             Neymar      92   25  ...              0             0                0
3        Luis Suárez      92   30  ...              0             0                0
4       Manuel Neuer      92   31  ...              0             0                1

[5 rows x 62 columns]

## 5. Applying a simple model to find similar players

Using cosine similarity

### 5.1 Normalizing the numerical columns

In [0]:
df8.columns

Index(['Name', 'Rating', 'Age', 'Weak_foot', 'Skill_Moves', 'Ball_Control',
       'Dribbling', 'Marking', 'Sliding_Tackle', 'Standing_Tackle',
       'Aggression', 'Reactions', 'Attacking_Position', 'Interceptions',
       'Vision', 'Composure', 'Crossing', 'Short_Pass', 'Long_Pass',
       'Acceleration', 'Speed', 'Stamina', 'Strength', 'Balance', 'Agility',
       'Jumping', 'Heading', 'Shot_Power', 'Finishing', 'Long_Shots', 'Curve',
       'Freekick_Accuracy', 'Penalties', 'Volleys', 'GK_Positioning',
       'GK_Diving', 'GK_Kicking', 'GK_Handling', 'GK_Reflexes', 'right_foot',
       'CAM', 'CB', 'CDM', 'CF', 'CM', 'LB', 'LM', 'LW', 'LWB', 'RB', 'RM',
       'RW', 'RWB', 'ST', 'High / High', 'High / Low', 'High / Medium',
       'Low / High', 'Low / Medium', 'Medium / High', 'Medium / Low',
       'Medium / Medium'],
      dtype='object')

In [0]:
df8_num = df8[['Rating', 'Age', 'Weak_foot', 'Skill_Moves',
       'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle',
       'Standing_Tackle', 'Aggression', 'Reactions', 'Attacking_Position',
       'Interceptions', 'Vision', 'Composure', 'Crossing', 'Short_Pass',
       'Long_Pass', 'Acceleration', 'Speed', 'Stamina', 'Strength', 'Balance',
       'Agility', 'Jumping', 'Heading', 'Shot_Power', 'Finishing',
       'Long_Shots', 'Curve', 'Freekick_Accuracy', 'Penalties', 'Volleys',
       'GK_Positioning', 'GK_Diving', 'GK_Kicking', 'GK_Handling',
       'GK_Reflexes']]

df8_num.head()

   Rating  Age  Weak_foot  ...  GK_Kicking  GK_Handling  GK_Reflexes
0      94   32          4  ...          15           11           11
1      93   29          4  ...          15           11            8
2      92   25          5  ...          15            9           11
3      92   30          4  ...          31           25           37
4      92   31          4  ...          95           90           89

[5 rows x 38 columns]

In [0]:
df8_cat = df8[['right_foot', 'CAM', 'CB', 'CDM', 'CF', 'CM', 'LB', 'LM',
       'LW', 'LWB', 'RB', 'RM', 'RW', 'RWB', 'ST', 'High / High', 'High / Low',
       'High / Medium', 'Low / High', 'Low / Medium', 'Medium / High',
       'Medium / Low', 'Medium / Medium']]

df8_cat.head()

   right_foot  CAM  CB  ...  Medium / High  Medium / Low  Medium / Medium
0           1    0   0  ...              0             0                0
1           0    0   0  ...              0             0                1
2           1    0   0  ...              0             0                0
3           1    0   0  ...              0             0                0
4           1    0   0  ...              0             0                1

[5 rows x 23 columns]

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df8_num_scaled_arr = scaler.fit_transform(df8_num)
df8_num_scaled = pd.DataFrame(df8_num_scaled_arr,columns=df8_num.columns)
df8_num_scaled.head()

     Rating       Age  Weak_foot  ...  GK_Kicking  GK_Handling  GK_Reflexes
0  3.929769  1.397344   1.625071  ...   -0.087849    -0.327688    -0.327226
1  3.788582  0.756330   1.625071  ...   -0.087849    -0.327688    -0.493579
2  3.647395 -0.098356   3.149676  ...   -0.087849    -0.445566    -0.327226
3  3.647395  0.970001   1.625071  ...    0.875990     0.497454     1.114498
4  3.647395  1.183672   1.625071  ...    4.731350     4.328471     3.997944

[5 rows x 38 columns]

In [0]:
df9 = pd.concat([df8.Name,df8_num_scaled,df8_cat],axis='columns')
df9.head()

                Name    Rating  ...  Medium / Low  Medium / Medium
0  Cristiano Ronaldo  3.929769  ...             0                0
1       Lionel Messi  3.788582  ...             0                1
2             Neymar  3.647395  ...             0                0
3        Luis Suárez  3.647395  ...             0                0
4       Manuel Neuer  3.647395  ...             0                1

[5 rows x 62 columns]

### 5.2 Creating the Vectors

In [0]:
## splitting the dataset into independent and dependent variables

X = df9.iloc[:,1:].values
Y = df9.iloc[:,0].values

print(X.shape, Y.shape)

(17588, 61) (17588,)

In [0]:
vectors = {}
for i,x in enumerate(X):
    vectors[i] = x.tolist()

## vector for cristano ronaldo
vectors[0]

[3.929768691361849,
 1.3973436472188534,
 1.6250713783654274,
 3.6144116528443435,
 2.0807062567740653,
 1.9667157620710607,
 -1.0310391362787488,
 -1.048847470231414,
 -0.7532390889121253,
 0.4058377742986423,
 3.690524477919895,
 2.2882986961280567,
 -0.8682516628232578,
 2.2134527113773608,
 2.235483543756971,
 1.8561026445925926,
 1.660655635806594,
 1.575597004009965,
 1.7811261670473981,
 1.8805492880246355,
 1.8429411694180418,
 1.1900249753362515,
 -0.07352917966355252,
 1.8329272472162537,
 2.6316892289126432,
 1.866108042603498,
 2.069291077837974,
 2.469427881087351,
 2.2172750581856913,
 1.8316231496349307,
 1.842597602904624,
 2.2578048749963155,
 2.5253285117700357,
 -0.15225840594708037,
 -0.5519334683763981,
 -0.08784941032295102,
 -0.3276883254756284,
 -0.32722589554897635,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

### 5.3 Cosine Similarities

[Explanation on cosine similarities](https://www.machinelearningplus.com/nlp/cosine-similarity/)

In [0]:
def cosine_similarity(vec1,vec2):
    a = np.array(vec1).ravel()
    b = np.array(vec2).ravel()
    denom = np.sqrt(np.sum(np.square(vec1))) * np.sqrt(np.sum(np.square(vec2)))
    return np.dot(a,b) / denom

In [0]:
cosine_similarity(vectors[0],vectors[1])

0.9007000448876162

In [0]:
from sklearn.metrics import pairwise as pw

index = 0
def similar_players(index=0,top=10):
    similarity_scores = {}
    for k,v in vectors.items(): 
        similarity_scores[k] = cosine_similarity(vectors[index],v)
    similarity_scores = sorted(similarity_scores.items(), key = lambda item: item[1], reverse=True)
    return similarity_scores[1:top+1]

In [0]:
basic_info2[basic_info2.iloc[:,0]=='De Gea'].index.values[0]

5

In [0]:
player = np.random.randint(0,100)
top_sim_players = similar_players(index=player,top=50)
print('Players similar to:',df9.loc[player,'Name'],":\n")


top_players = {}
for index,similarity in top_sim_players:
    info = list(basic_info2.loc[index,['Name','Age','Preffered_Position','Rating']].values)
    info.insert(len(info),similarity)
    top_players[index] = info

output = pd.DataFrame.from_dict(data=top_players, orient='index',columns=['Name','Age','Preferred Position','Rating','Similarity'])
output.sort_values(by=['Similarity'],ascending=False)

Players similar to: Petr Čech :

                         Name Age Preferred Position Rating  Similarity
269             Benoît Costil  29                 GK     82    0.973518
273               Diego López  35                 GK     82    0.972594
113            Steve Mandanda  32                 GK     84    0.970341
258          Emiliano Viviano  31                 GK     82    0.966282
663             Sergio Romero  30                 GK     79    0.965730
513           Antonio Mirante  33                 GK     80    0.965346
81           Stéphane Ruffier  30                 GK     85    0.964515
510             Igor Akinfeev  30                 GK     80    0.963718
521                René Adler  32                 GK     80    0.963592
506                Ben Foster  33                 GK     80    0.962991
705                Tim Howard  38                 GK     79    0.962699
311          Jasper Cillessen  27                 GK     81    0.962631
337         Wojciech Szczęsny  26                 GK     81    0.962154
835                 Guilherme  31                 GK     78    0.961884
40           Samir Handanovič  32                 GK     87    0.961751
9            Thibaut Courtois  24                 GK     89    0.961421
619               Jeroen Zoet  26                 GK     79    0.961307
701            Diego Benaglio  33                 GK     79    0.960459
868                Tom Heaton  30                 GK     79    0.960240
5                      De Gea  26                 GK     90    0.958659
373           Cédric Carrasso  35                 GK     81    0.957779
47                 Bernd Leno  25                 GK     86    0.957501
512             Andriy Pyatov  32                 GK     80    0.957493
378   Rune Almenning Jarstein  32                 GK     81    0.957033
468         Ron-Robert Zieler  28                 GK     80    0.956158
449            Oliver Baumann  26                 GK     80    0.956090
788             Koen Casteels  24                 GK     78    0.955832
886           Sergey Ryzhikov  36                 GK     78    0.955014
321            Lukáš Hrádecký  27                 GK     81    0.954108
190                José Reina  34                 GK     83    0.953970
1991           David Marshall  32                 GK     75    0.953967
524        Stefano Sorrentino  38                 GK     80    0.953967
1131          Mariano Andújar  33                 GK     77    0.953014
505          Łukasz Fabiański  31                 GK     80    0.952820
31           Gianluigi Buffon  39                 GK     88    0.952205
1920         Przemysław Tytoń  30                 GK     75    0.952103
1155                   Sergio  30                 GK     77    0.951854
516               Michel Vorm  33                 GK     80    0.951583
1599     Maarten Stekelenburg  34                 GK     76    0.951492
109             Ralf Fährmann  28                 GK     84    0.951376
165               Yann Sommer  28                 GK     83    0.951327
67               Keylor Navas  30                 GK     85    0.950851
281             Victor Valdés  35                 GK     82    0.950777
150               Roman Bürki  26                 GK     83    0.950731
171             Asmir Begović  29                 GK     83    0.950686
499          Salvatore Sirigu  30                 GK     80    0.950640
1532        Mikhail Kerzhakov  30                 GK     76    0.950472
180         Kasper Schmeichel  30                 GK     83    0.950212
644                   Roberto  31                 GK     79    0.949840
2424        Mitchell Langerak  28                 GK     74    0.949163

## 6. Exporting the data file as json


difference between dump and dumps - 

dump() method (without “s” in “dump”) used to write Python serialized object as JSON formatted data into a file. The file type can be anything including text, JSON or even binary file. The json. dumps() method encodes any Python object into JSON formatted String

In [0]:
type(basic_info_dict[0])

list

In [0]:
import json

## dumping the player basic information as json
with open('players.json','w') as json_file:
    json.dump(basic_info_dict, json_file)

## dumping the player attributes as json file
with open('players_attributes.json','w') as json_file:
    json.dump(vectors,json_file)

## UI Design

**Title of the webpage:**

Football Player Scout

**Input:**

Show me **10** players similar to __________ cristano ronaldo

**output:**

10 players listed with their basic features like overall, nationality, height, weight, current club and preferred positions.
(that can be taken from the available dataset)

Addons - 
1. link to youtube video skills and moves
2. photo from sites like transfermkt and other relevant and important information of the player like the current market value

In [0]:
x = df.copy()
x.head()

                Name Nationality  ... GK_Handling  GK_Reflexes
0  Cristiano Ronaldo    Portugal  ...          11           11
1       Lionel Messi   Argentina  ...          11            8
2             Neymar      Brazil  ...           9           11
3        Luis Suárez     Uruguay  ...          25           37
4       Manuel Neuer     Germany  ...          90           89

[5 rows x 53 columns]

In [0]:
x.index = x.index.astype(float)

In [0]:
x.head()

                  Name Nationality  ... GK_Handling  GK_Reflexes
0.0  Cristiano Ronaldo    Portugal  ...          11           11
1.0       Lionel Messi   Argentina  ...          11            8
2.0             Neymar      Brazil  ...           9           11
3.0        Luis Suárez     Uruguay  ...          25           37
4.0       Manuel Neuer     Germany  ...          90           89

[5 rows x 53 columns]